project_name: starlink_exporter

before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - main: ./cmd/starlink_exporter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7

archives:
  #  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  #    replacements:
  #      darwin: Darwin
  #      linux: Linux
  #      windows: Windows
  #      amd64: x86_64
  #    format_overrides:
  #      - goos: windows
  #        format: zip
  #    files:
  #      - none*

  - name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- if eq .Os "Darwin" }}macos_
      {{- else }}{{- tolower .Os }}_{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}
      {{ if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

    #dockers:
    #  - image_templates:
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-amd64
    #    use: buildx
    #    dockerfile: Dockerfile
    #    build_flag_templates:
    #      - "--platform=linux/amd64"
    #
    #  - image_templates:
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm7
    #    use: buildx
    #    dockerfile: Dockerfile
    #    goarch: arm
    #    goarm: 7
    #    build_flag_templates:
    #      - "--platform=linux/arm/v7"
    #
    #  - image_templates:
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm64
    #    use: buildx
    #    dockerfile: Dockerfile
    #    goarch: arm64
    #    build_flag_templates:
    #      - "--platform=linux/arm64/v8"
    #
    #docker_manifests:
    #  # dockerhub
    #  - name_template: sysdigdan/{{.ProjectName}}:v{{ .Version }}
    #    image_templates:
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-amd64
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm64
    # - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm7
    #  - name_template: sysdigdan/{{.ProjectName}}:latest
    #    image_templates:
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-amd64
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm64
    #      - sysdigdan/{{.ProjectName}}:v{{ .Version }}-arm7
