name: build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
      branches:
        - main
  schedule:
    - cron: '0 14 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


