name: build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
      branches:
        - main
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: docker buildx setup
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: StarkZarn
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/starkzarn/starlink_exporter:latest
          push: true

